language: node_js
node_js:
  - 0.10.36
before_install:
  - npm install -g grunt-cli
  - npm install -g kss
install: npm install
before_script: grunt dist
script: 
  - if [ "$TRAVIS_BRANCH" == "master" ]; then bash ./deploy-ghpages.sh; fi
env:
  global:
    - GH_REF: github.com/Teleopti/styleguide.git
    - secure: d9ejf1F4Q+kIhKVfaReYlW3itLeMmQzcuJH4vM/LffzJb/PusyI+mMBmo4Bc4h3GmkJEjCb78nrxjzRFZeG3C7C4jOgg2NGGIwQzpHoKcziwmfpX8BgFTnBU6VlmLUBnNxOINppLV6glMR0kHK6o/KLrKC56xKzHX4/yYrXcPdQ=
